[package]
name = "glenn-rs"
version = "0.1.0"
authors = ["Henrik Larsson <reg@henkelarsson.se>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
